# ============================================
# SECRET - Sensitive configuration
# File: k8s/secrets/common-secrets.yaml
# NOTE: Values must be base64 encoded
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: ilpd-mis
type: Opaque
data:
  # Postgres secrets
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=

  # Mongo secrets
  MONGO_USER: bW9uZ28=
  MONGO_PWD: bW9uZ28=
  MONGO_AUTH_DB: YWRtaW4=

  # RabbitMQ secrets
  RABBIT_USER: bm90aWZpY2F0aW9uX3VzZXI=
  RABBIT_PWD: bm90aWZpY2F0aW9uX3Bhc3M=

  # Spring mail secrets
  SPRING_MAIL_USERNAME: ZXhhbXBsZUBnbWFpbC5jb20=
  SPRING_MAIL_PASSWORD: cGFzc3dvcmQ=
