# ============================================
# CONFIGMAP - Non-sensitive configuration
# File: k8s/configmaps/inventory-service-configmap.yaml
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-configmap
  namespace: ilpd-mis
data:
  # Application configuration
  SERVER_PORT: "8088"
  
  # Database configuration (URL only, no credentials)
  DB_URL: "jdbc:postgresql://localhost:5433/inventory_db"

  PROFILE_MODE: "dev"

  # Mongo Configurations
  INVENTORY_DB: "inventory_db"
